apiVersion: v1
kind: Service
metadata: 
  name: hello-svc
  labels:
    app: hello-set
spec:
  selector:
    app: hello-set
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
status:
  loadBalancer:
      ingress:
      - ip: 172.17.113.200
  
